services:
  - type: web
    name: jobscout-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_HOSTBUILDER_RELOADCONFIGONCHANGE
        value: "false"
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
      - key: DOTNET_EnableDiagnostics
        value: "0"
